root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "./tmp/k8sman"
cmd = "go build -tags=citizix,k8sman -trimpath '-ldflags=-s -w -X=k8sman/internal/buildinfo.BuildID=1 -X=k8sman/internal/buildinfo.BuildTag=latest -extldflags=-static' -o=./tmp/k8sman ./cmd/server/main.go"
delay = 1000
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "ui",
    "deploy",
    "migrations",
    "scripts",
    "web",
    "api",
    "client",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
