name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
    - main

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-push:
    name: docker-build-push
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Declare docker tag variable
      id: vars
      shell: bash
      run: |
        GIT_HASH=$(git rev-parse --short "${GITHUB_SHA}")
        echo "##[set-output name=docker_tag;]$(echo ${GITHUB_REF##*/}-${GIT_HASH})"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        build-args: |
          TAGS=k8sman
          BUILD_ID=${{ github.run_id }}
          BUILD_TAG=${{ steps.vars.outputs.docker_tag }}
          BUILD_TIME="${{ steps.current-time.outputs.time }}"
        tags: ektowett/k8sman:${{ steps.vars.outputs.docker_tag }}

    - name: Notify slack of deploy status
      uses: lazy-actions/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: "*k8sman build - ${{ steps.vars.outputs.docker_tag }}*"
        mention: 'here'
        mention_if: 'failure'
        channel: '#deploys'
        url: ${{ secrets.SLACK_WEBHOOK }}
